//UMA EMPRESA DE TRANSPORTE DE PESSOAS POR APLICATIVO DESEJA CRIAR UM CADASTRO DE MOTORISTA.
//NESTE CADASTRO, O MOTORISTA PRECISA ENVIAR ALGUNS DOCUMENTOS/INFORMAÇOES,TAIS COMO: NOME, ATESTADO ANTECEDENTES, IDADE, NACIONALIDADE
//ATRAVEZ DO JAVASCRIPT, CRIE UM CÓDIGO QUE RETORNE AO USUARIO SE ELE PODE SE CADASTRAR OU NÃO SABENDO QUE O MOTORISTA :
//NÃO PODE TER ATESTADO DE ANTECEDENTES(SEM FIXA CRIMINAL)
//PRECISA SER MAIOR QUE 18 ANOS
//PRECISA SER BRASILEIRO



//DICAS
//CRIE UM OBJETO CHAMADO MOTORISTA COM 4 ATRIBUTOS: NOME, ATESTADO ANTECEDENTES, IDADE, NACIONALIDADE
//CRIE OPERADORES CONDICIONANTES APRENDIDOS NA AULA PASSADA PARA VERIFICAR OS VALORES DO OBJETO.
