//UMA EMPRESA DE TRANSPORTE DE PESSOAS POR APLICATIVO DESEJA CRIAR UM CADASTRO DE MOTORISTA.
//NESTE CADASTRO, O MOTORISTA PRECISA ENVIAR ALGUNS DOCUMENTOS/INFORMAÇOES,TAIS COMO: NOME, ATESTADO ANTECEDENTES, IDADE, NACIONALIDADE
//ATRAVES DO JAVASCRIPT, CRIE UM CÓDIGO QUE RETORNE AO USUARIO SE ELE PODE OU NÃO SE CADASTRAR, SABENDO QUE O MOTORISTA :
//1-NÃO PODE TER ATESTADO DE ANTECEDENTES(SEM FIXA CRIMINAL)
//2-PRECISA SER MAIOR QUE 18 ANOS
//3-PRECISA SER BRASILEIRO OU AGENTINO

//OBS O CÓDIGO DEVE MOSTRAR AO USUÁRIO O MOTIVO PELO QUAL NÃO PODE SER CADASTRADO

